#!/usr/bin/env python3
"""
University of Twente Assignment PDF Parser
Extracts hidden metadata from assignment PDFs generated by the UT Assignment Formatting Assistant
"""

import json
import re
import base64
from pathlib import Path
from typing import Dict, List, Optional, Union
from datetime import datetime
import argparse

# PDF parsing libraries
try:
    import PyPDF2
except ImportError:
    print("Please install PyPDF2: pip install PyPDF2")
    exit(1)

try:
    from pdfplumber import PDF
    HAS_PDFPLUMBER = True
except ImportError:
    HAS_PDFPLUMBER = False
    print("Warning: pdfplumber not installed. Install with: pip install pdfplumber")
    print("Falling back to PyPDF2 (less reliable for hidden text)")

# Optional: For JSON schema validation
try:
    import jsonschema
    HAS_JSONSCHEMA = True
except ImportError:
    HAS_JSONSCHEMA = False
    print("Warning: jsonschema not installed. Install with: pip install jsonschema")


class AssignmentPDFParser:
    """Parser for University of Twente assignment PDFs with embedded metadata"""
    
    def __init__(self, schema_path: Optional[str] = None):
        self.schema = None
        if schema_path and HAS_JSONSCHEMA:
            with open(schema_path, 'r') as f:
                self.schema = json.load(f)
    
    def extract_metadata_pypdf2(self, pdf_path: str) -> Optional[Dict]:
        """Extract metadata using PyPDF2 (fallback method)"""
        try:
            with open(pdf_path, 'rb') as file:
                pdf_reader = PyPDF2.PdfReader(file)
                
                # Collect all text from all pages
                full_text = ""
                for page_num in range(len(pdf_reader.pages)):
                    page = pdf_reader.pages[page_num]
                    full_text += page.extract_text()
                
                return self._parse_metadata_from_text(full_text)
        
        except Exception as e:
            print(f"Error with PyPDF2: {e}")
            return None
    
    def extract_metadata_pdfplumber(self, pdf_path: str) -> Optional[Dict]:
        """Extract metadata using pdfplumber (preferred method)"""
        if not HAS_PDFPLUMBER:
            return None
        
        try:
            with PDF.open(pdf_path) as pdf:
                full_text = ""
                for page in pdf.pages:
                    # Extract all text, including white/hidden text
                    text = page.extract_text(x_tolerance=1, y_tolerance=1)
                    if text:
                        full_text += text
                    
                    # Also try to extract from page objects directly
                    for obj in page.chars:
                        # Check for white text (RGB 255,255,255)
                        if hasattr(obj, 'non_stroking_color'):
                            color = obj.get('non_stroking_color', [])
                            if color == [1, 1, 1]:  # White color
                                full_text += obj.get('text', '')
                
                return self._parse_metadata_from_text(full_text)
        
        except Exception as e:
            print(f"Error with pdfplumber: {e}")
            return None
    
    def _parse_metadata_from_text(self, text: str) -> Optional[Dict]:
        """Parse metadata from extracted text"""
        # Look for metadata markers
        start_marker = "###METADATA_START###"
        end_marker = "###METADATA_END###"
        minimal_marker = "###METADATA_MINIMAL###"
        truncated_marker = "###METADATA_TRUNCATED###"
        
        # First check for minimal metadata (fallback)
        if minimal_marker in text:
            minimal_idx = text.find(minimal_marker)
            minimal_text = text[minimal_idx + len(minimal_marker):]
            # Extract until end of line or reasonable length
            minimal_text = minimal_text.split('\n')[0][:500]
            try:
                return json.loads(minimal_text)
            except:
                print("Found minimal metadata marker but couldn't parse")
        
        start_idx = text.find(start_marker)
        end_idx = text.find(end_marker)
        
        # Check for truncated metadata
        if start_idx != -1 and truncated_marker in text:
            print("Warning: Metadata was truncated")
            end_idx = text.find(truncated_marker)
        
        if start_idx == -1:
            print("Metadata markers not found in PDF")
            # Try to find any JSON-like structure at the end of the document
            json_pattern = r'\{[^{}]*"generatedAt"[^{}]*\}'
            matches = re.findall(json_pattern, text[-5000:], re.DOTALL)
            if matches:
                print("Found JSON-like structure without markers")
                try:
                    return json.loads(matches[-1])
                except:
                    pass
            return None
        
        # Extract metadata between markers
        if end_idx == -1:
            # No end marker, try to extract what we can
            metadata_text = text[start_idx + len(start_marker):]
            # Try to find the end of JSON
            brace_count = 0
            json_end = 0
            for i, char in enumerate(metadata_text):
                if char == '{':
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
                    if brace_count == 0:
                        json_end = i + 1
                        break
            metadata_text = metadata_text[:json_end]
        else:
            metadata_text = text[start_idx + len(start_marker):end_idx]
        
        # Clean up the text - be more careful about whitespace
        # Only remove newlines and extra spaces, not all whitespace
        metadata_text = metadata_text.replace('\n', '').replace('\r', '')
        metadata_text = re.sub(r'\s{2,}', ' ', metadata_text)
        
        try:
            metadata = json.loads(metadata_text)
            
            # Validate against schema if available
            if self.schema and HAS_JSONSCHEMA:
                jsonschema.validate(metadata, self.schema)
            
            return metadata
        
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON metadata: {e}")
            print(f"Metadata text (first 500 chars): {metadata_text[:500]}")
            return None
        except jsonschema.ValidationError as e:
            print(f"Metadata validation error: {e}")
            return metadata
    
    def parse_pdf(self, pdf_path: str) -> Optional[Dict]:
        """Parse PDF and extract metadata using the best available method"""
        # Try pdfplumber first (better for hidden text)
        if HAS_PDFPLUMBER:
            metadata = self.extract_metadata_pdfplumber(pdf_path)
            if metadata:
                return metadata
        
        # Fall back to PyPDF2
        return self.extract_metadata_pypdf2(pdf_path)
    
    def save_images(self, metadata: Dict, output_dir: str = "extracted_images"):
        """Extract and save all base64 images from metadata"""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)
        
        for q_idx, question in enumerate(metadata.get('questions', [])):
            # Save uploaded images
            if question.get('uploadedImage'):
                self._save_base64_image(
                    question['uploadedImage'],
                    output_path / f"q{q_idx + 1}_uploaded.jpg"
                )
            
            # Extract and save embedded images from HTML
            html_content = question.get('answerHTML', '')
            img_pattern = r'<img[^>]+src="(data:image/[^;]+;base64,[^"]+)"'
            
            for img_idx, match in enumerate(re.finditer(img_pattern, html_content)):
                base64_data = match.group(1)
                self._save_base64_image(
                    base64_data,
                    output_path / f"q{q_idx + 1}_embedded_{img_idx + 1}.jpg"
                )
    
    def _save_base64_image(self, base64_str: str, filepath: Path):
        """Save a base64 image string to file"""
        try:
            # Extract the base64 data part
            if ',' in base64_str:
                header, data = base64_str.split(',', 1)
                # Determine file extension from header
                if 'png' in header:
                    filepath = filepath.with_suffix('.png')
                elif 'gif' in header:
                    filepath = filepath.with_suffix('.gif')
                elif 'webp' in header:
                    filepath = filepath.with_suffix('.webp')
            else:
                data = base64_str
            
            # Decode and save
            img_data = base64.b64decode(data)
            filepath.write_bytes(img_data)
            print(f"Saved image: {filepath}")
        
        except Exception as e:
            print(f"Failed to save image {filepath}: {e}")
    
    def generate_report(self, metadata: Dict) -> str:
        """Generate a human-readable report from metadata"""
        report = []
        report.append("=" * 60)
        report.append("ASSIGNMENT SUBMISSION REPORT")
        report.append("=" * 60)
        
        report.append(f"\nTitle: {metadata.get('title', 'N/A')}")
        report.append(f"Generated: {metadata.get('generatedAt', 'N/A')}")
        
        student = metadata.get('student', {})
        report.append(f"\nStudent Information:")
        report.append(f"  Name: {student.get('name', 'N/A')}")
        report.append(f"  S-Number: {student.get('snumber', 'N/A')}")
        report.append(f"  Group: {student.get('group', 'N/A')}")
        report.append(f"  Date: {student.get('date', 'N/A')}")
        
        if metadata.get('instructions'):
            report.append(f"\nInstructions: {metadata['instructions']}")
        
        report.append(f"\nTotal Questions: {metadata.get('questionCount', 0)}")
        report.append("\n" + "-" * 60)
        
        for q in metadata.get('questions', []):
            report.append(f"\nQuestion {q['questionNumber']}: {q['questionText']}")
            if q.get('questionDescription'):
                report.append(f"Description: {q['questionDescription']}")
            
            # Show answer preview (first 200 chars)
            answer_preview = q['answerPlainText'][:200]
            if len(q['answerPlainText']) > 200:
                answer_preview += "..."
            report.append(f"Answer: {answer_preview}")
            
            # Check for images
            has_uploaded = bool(q.get('uploadedImage'))
            embedded_count = len(re.findall(r'<img', q.get('answerHTML', '')))
            
            if has_uploaded or embedded_count > 0:
                img_info = []
                if has_uploaded:
                    img_info.append("1 uploaded image")
                if embedded_count > 0:
                    img_info.append(f"{embedded_count} embedded image(s)")
                report.append(f"Images: {', '.join(img_info)}")
            
            report.append("-" * 40)
        
        return "\n".join(report)


def main():
    parser = argparse.ArgumentParser(
        description="Extract metadata from University of Twente assignment PDFs"
    )
    parser.add_argument("pdf_path", help="Path to the PDF file")
    parser.add_argument(
        "--schema", 
        help="Path to JSON schema file for validation",
        default="metadata_schema.json"
    )
    parser.add_argument(
        "--save-images", 
        action="store_true",
        help="Extract and save all images"
    )
    parser.add_argument(
        "--image-dir",
        default="extracted_images",
        help="Directory to save extracted images (default: extracted_images)"
    )
    parser.add_argument(
        "--json-output",
        help="Save metadata to JSON file"
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Generate human-readable report"
    )
    
    args = parser.parse_args()
    
    # Initialize parser
    pdf_parser = AssignmentPDFParser(
        schema_path=args.schema if Path(args.schema).exists() else None
    )
    
    # Parse PDF
    print(f"Parsing PDF: {args.pdf_path}")
    metadata = pdf_parser.parse_pdf(args.pdf_path)
    
    if not metadata:
        print("Failed to extract metadata from PDF")
        return 1
    
    print("Successfully extracted metadata!")
    
    # Save images if requested
    if args.save_images:
        print(f"\nExtracting images to {args.image_dir}/")
        pdf_parser.save_images(metadata, args.image_dir)
    
    # Save JSON if requested
    if args.json_output:
        with open(args.json_output, 'w') as f:
            json.dump(metadata, f, indent=2)
        print(f"\nMetadata saved to: {args.json_output}")
    
    # Generate report if requested
    if args.report:
        report = pdf_parser.generate_report(metadata)
        print("\n" + report)
    
    # Always show basic info
    if not args.report:
        print(f"\nTitle: {metadata.get('title')}")
        print(f"Student: {metadata.get('student', {}).get('name', 'N/A')}")
        print(f"Questions: {metadata.get('questionCount')}")
    
    return 0


if __name__ == "__main__":
    exit(main())